name: Evo CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.1'
    - uses: actions/setup-node@v1
      with:
          node-version: '14.0.0'
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.23.6
    - run: pnpm run setup
    - run: ./node_modules/.bin/evo run ci

